### PR TITLE
SFR-1064 New Handlers

### PR DESCRIPTION
**Pull request by mwbenowitz**
This adds two new handlers for deployment options for the conversion service. The first provides handlers that can be invoked via the AWS Lambda service and the second provides a generic means of deploying the API as a containerized service. These handlers provide exactly the same method calls as the vercel handlers, differing only in how the responses are constructed/sent.

These handlers are documented in the CHANGELOG and some new dependencies have been added, though these should have no impact in how the service is deployed to vercel.

Some questions to address before approving/merging:
- What should the testing strategy be for these handlers? The actual conversion method calls are tested already so it should only need to confirm that each handler accepts the path parameter properly and returns the expected status code and payload
- Is additional documentation needed/preferred?
- The types in the `validateParam` method had to be extended somewhat, is this potentially an issue?

### CODE REVIEW

**Review by kristojorg — APPROVED** [review]
Looks great to me, thanks for doing this!

**Comment by kristojorg** [comment]
It looks like we need to update the github actions scrips to ignore the optional dependency on the private @nypl-simplified-packages/axisnow-access-control-web manually. I will make a commit doing that if that's okay

**Comment by mwbenowitz** [comment]
@kristojorg yeah that makes sense to me, I was wondering why that was failing

**Comment by mwbenowitz** [comment]
Looks like the error that is causing the failures is coming from a test suite that is skipped anyway, could the offending import/require just be commented out? If the tests are enabled and it's still commented the tests will fail, which would ensure that it's not forgotten about.

**Comment by kristojorg** [comment]
@mwbenowitz yep that would have been the logical and easiest thing to do 😓  ... if my current change doesn't fix it then I'll just do that

**Comment by kristojorg** [comment]
If you wanted to write some tests for the handlers you wrote that would be awesome, but I'll let you make the call on whether it's necessary or not : ). It looked like my fix worked so feel free to merge if you don't think the tests are necessary.

**Comment by mwbenowitz** [comment]
Added the tests and they pass but the ubuntu runs hang, not sure why

**Review by kristojorg — APPROVED** [review]
Looks good to me!

**Pull request merged**
